In [1]:
import os
import tensorflow as tf

In [8]:
def read_and_decode(filename_queue):
    tf_record_reader=tf.TFRecordReader()
    _, tf_record_serialized = tf_record_reader.read(tf_record_filename_queue)

    tf_record_features = tf.parse_single_example(
        tf_record_serialized,
        features={
            'label': tf.FixedLenFeature([], tf.string),
            'width': tf.FixedLenFeature([], tf.int64),
            'height': tf.FixedLenFeature([], tf.int64),
            'image': tf.FixedLenFeature([], tf.string),
        })
    tf_record_image = tf.decode_raw(tf_record_features['image'],tf.uint8)

    tf_record_image = tf.reshape(tf_record_image, [64,64])

    tf_record_label = tf.cast(tf_record_features['label'],tf.string)

    images, labels = tf.train.shuffle_batch([tf_record_image, tf_record_label],
                                         batch_size=10,
                                         capacity=30,
                                         num_threads=5,
                                         min_after_dequeue=10 )
    return images, labels

In [3]:
tf_record_filename_queue = tf.train.string_input_producer(tf.train.match_filenames_once("./s_HanDB_Test.tfrecord"))
#f=open("./test_record.tfrecord",'rb')

In [4]:
tf_record_reader=tf.TFRecordReader()
_, tf_record_serialized = tf_record_reader.read(tf_record_filename_queue)

In [5]:
tf_record_features = tf.parse_single_example(
    tf_record_serialized,
    features={
        'label': tf.FixedLenFeature([], tf.string),
        'width': tf.FixedLenFeature([], tf.int64),
        'height': tf.FixedLenFeature([], tf.int64),
        'image': tf.FixedLenFeature([], tf.string),
    })

In [10]:
#tf_record_image = tf.decode_raw(tf_record_features['image'],tf.uint8)

#tf_record_image = tf.reshape(tf_record_image, [64,64,1])

#tf_record_label = tf.cast(tf_record_features['label'],tf.string)

images, labels = read_and_decode(tf_record_filename_queue)

init=tf.local_variables_initializer()
print(images)
with tf.Session() as sess:
    sess.run(init)
    coord=tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    for i in range(3):
        img, lab = sess.run([images,labels])
        print(img)
    
    coord.request_stop()
    coord.join(threads)



Tensor("shuffle_batch_2:0", shape=(10, 64, 64), dtype=uint8)
[[[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255  40 ... 255 255 255]
  ...
  [255 255 255 ...   0  12 255]
  [255 255 255 ...   0   0 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ...  71  71 255]
  [255 255 255 ...  73  73 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]]

 ...

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ...  36  71 255]
  [255 255 255 ...  36 109 255]
  [255 255 255 ... 255 255 255]]

 [[255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  [255 255 255 ... 255 255 255]
  ...
  [255 255 255 ... 255 255 255]